import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { VercelToolbar } from "@vercel/toolbar/next";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white text-3xl`}>
        {children}
        <VercelToolbar />
      </body>
    </html>
  );
}
